"""Starter code for HW2 Problem 5: run a ConstraintFlow certifier on MNIST.

Example:
    python run_cf.py deeppoly.cf --eps 0.01 0.02 0.03 --num-images 100

If your shape has members other than l, u, L, U (or Z), tell the script how
to initialize them at the input layer. For example, if you add a second
polyhedral lower bound La that starts as the input box, use:
    python run_cf.py mycert.cf --init La=L

For each epsilon, the script checks local robustness of the first
--num-images test images in the L-infinity ball of radius epsilon.
An image is verified if the certifier proves that the logit of the true
label is larger than every other logit for all inputs in the ball.
"""
import argparse
import contextlib
import io
import os
import sys
import time

import onnx
import torch
from onnx import numpy_helper
from torchvision import datasets, transforms

from constraintflow.compiler.compile import compile as cf_compile
from constraintflow.lib.globals import set_device

MEAN, STD = 0.1307, 0.3081


def onnx_predict(network_file, x):
    """Run the ONNX network (Flatten, Gemm, Relu only) with PyTorch."""
    model = onnx.load(network_file)
    params = {t.name: torch.tensor(numpy_helper.to_array(t)) for t in model.graph.initializer}
    h = ((x - MEAN) / STD).reshape(x.shape[0], -1)
    for node in model.graph.node:
        if node.op_type == "Gemm":
            h = h @ params[node.input[1]].T + params[node.input[2]]
        elif node.op_type == "Relu":
            h = torch.relu(h)
    return h.argmax(dim=1)


def add_initializations(main_file, inits):
    """The compiler initializes only l, u, L, U and Z at the input layer.
    Insert "NAME = copy.deepcopy(EXISTING)" for each other shape member."""
    if not inits:
        return
    with open(main_file) as f:
        lines = f.read().split("\n")
    i = next(k for k, line in enumerate(lines) if "get_network_and_input_spec(" in line)
    indent = lines[i][:len(lines[i]) - len(lines[i].lstrip())]
    new = [f"{indent}import copy"]
    for item in inits:
        name, existing = item.split("=")
        new.append(f"{indent}{name} = copy.deepcopy({existing})")
    lines[i + 1:i + 1] = new
    with open(main_file, "w") as f:
        f.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("program", help="ConstraintFlow (.cf) file of the certifier")
    parser.add_argument("--network", default="mnist_relu_3_100.onnx")
    parser.add_argument("--eps", type=float, nargs="+", default=[0.005, 0.01, 0.02, 0.03, 0.05])
    parser.add_argument("--num-images", type=int, default=100)
    parser.add_argument("--data", default="./data")
    parser.add_argument("--output-path", default=None,
                        help="Directory for the compiled certifier (default: build_<program name>/)")
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--init", nargs="*", default=[], metavar="NAME=EXISTING",
                        help="Initialize a new shape member NAME at the input layer "
                             "as a copy of EXISTING (one of l, u, L, U, Z)")
    args = parser.parse_args()

    set_device(args.device)
    name = os.path.splitext(os.path.basename(args.program))[0]
    output_path = args.output_path or f"build_{name}"
    os.makedirs(output_path, exist_ok=True)

    # 1. Compile the certifier to Python code.
    cf_compile(args.program, output_path)
    add_initializations(os.path.join(output_path, "main.py"), args.init)
    sys.path.insert(0, os.path.abspath(output_path))
    from main import run  # generated by the compiler

    # 2. Load the test images. ConstraintFlow normalizes the input box itself.
    test = datasets.MNIST(args.data, train=False, download=True, transform=transforms.ToTensor())
    X = torch.stack([test[i][0] for i in range(args.num_images)]).to(args.device)
    y = torch.tensor([test[i][1] for i in range(args.num_images)]).to(args.device)
    correct = (onnx_predict(args.network, X.cpu()) == y.cpu())
    print(f"Network: {args.network}")
    print(f"Clean accuracy on {args.num_images} images: {correct.float().mean().item():.2%}")

    # 3. Run the certifier for each epsilon, one image at a time.
    print(f"{'eps':>8} {'verified':>10} {'time/img (s)':>14}")
    for eps in args.eps:
        verified = 0
        start = time.perf_counter()
        for i in range(args.num_images):
            with contextlib.redirect_stdout(io.StringIO()):  # hide "Network loaded"
                lb, _ = run(args.network, 1, eps, X[i:i + 1], y[i:i + 1], dataset="mnist",
                            train=False, print_intermediate_results=False, no_sparsity=False)
            # lb[j] is a lower bound of logit[y] - logit[j] for each other class j.
            verified += int((lb >= 0).all().item())
        elapsed = (time.perf_counter() - start) / args.num_images
        print(f"{eps:>8} {verified / args.num_images:>10.2%} {elapsed:>14.4f}")


if __name__ == "__main__":
    main()
